# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CHl_BaI9wjyhWsR3PCpqXH9yT3tIhgC8
"""

from functools import wraps
import time


def time_this(func):
    @wraps(func)
    def timeit_wrapper(*args, **kwargs):
        start_time = time.perf_counter()
        result = func(*args, **kwargs)
        end_time = time.perf_counter()
        total_time = end_time - start_time
        print(f'Function {func.__name__} ran in {total_time:.4f} seconds')
        return result
    return timeit_wrapper


@time_this
def calculateSomething(num):
    total = sum((x for x in range(0, num**2)))
    return total

if __name__ == '__main__':
    calculateSomething(10)
    calculateSomething(100)
    calculateSomething(1000)
    calculateSomething(5000)
    calculateSomething(10000)
