# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hCF79yLykIausPQUEvev9v8KBL7trTAO
"""

ascii_dict = {'A': 65, 'B': 66, 'C': 67, 'D': 68}

inv_dict = {v: k for k, v in ascii_dict.items()}

print("Reverse mapped dictionary : ", str(inv_dict))