# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18t845u0sXsZV5QRhHsPy76KtJDF29scD
"""

sentence = 'Python is Awesome'

upperCaseIndex = []
length = len(sentence)
print(length)

global j
j = -1
for i in range(length):
  j += 1
  if sentence[i].isupper():
     upperCaseIndex.append(j)

print(upperCaseIndex)

newSentence = sentence.lower()

def reverseword(s): 
   w = s.split(" ")        
   new = [i[::-1] for i in w]                   
   reversedString = " ".join(new)

   global k
   k = -1
   for i in range(length):
      k += 1
      if k in upperCaseIndex:
        reversedString = reversedString[:k] + reversedString[k].upper() + reversedString[k + 1:]
        
     
   print(reversedString)

reverseword(newSentence)
