# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A0REMT0vCrTzflUJuhw6nnJXL0T0m_kZ
"""

##################------------PYTHON HANGMAN-------#########################
import random

print("----------------------------LET'S PLAY HANGMAN-----------------------------------")

def getRandomWord():
    words = ['apple', 'banana', 'mango', 'strawberry', 'orange', 'grape', 'pineapple', 'watermelon']

    word = random.choice(words)
    return word


def displayBoard(missedLetters, correctLetters, secretWord):
    print("---------------------------------------------------------------------------------------------------------------------------------------------")
    
    print('The word to guess is : ')

    blanks = '_' * len(word)

    for i in range(len(word)):  # replace blanks with correctly guessed letters
        if word[i] in correctLetters:
            blanks = blanks[:i] + word[i] + blanks[i+1:]

    for letter in blanks:  # show the secret word with spaces in between each letter
        print(letter, end=' ')
    print("\n")

    print('Missed Letters:', sorted(missedLetters))
    
    print('Correct Letters:', sorted(correctLetters))
    print('\n')


def getGuess(alreadyGuessed): #input letter conditions
    while True:
        guess = input('Guessed letter: ')
        guess = guess.lower()

        if len(guess) != 1:
            print('Please enter a single letter.')

        elif guess in alreadyGuessed:
            print('You have already guessed that letter. Choose again.')

        elif guess not in 'abcdefghijklmnopqrstuvwxyz':
            print('Please enter a LETTER.')

        else:
            return guess



missedLetters = ''
correctLetters = ''
word = getRandomWord()
gameIsDone = False
global count
count = 0
global limit
limit = 6

while True:
    displayBoard( missedLetters, correctLetters, word)

    guess = getGuess(missedLetters + correctLetters)

    if guess in word:
        correctLetters = correctLetters + guess

        foundAllLetters = True
        for i in range(len(word)):
            if word[i] not in correctLetters:
                foundAllLetters = False
                break
        if foundAllLetters:
            print('\nYes! The secret word is "' +
                  word + '"! You have won!')
            gameIsDone = True
    else:
        missedLetters = missedLetters + guess
        count += 1

        if count == 1:
            print("Wrong guess. " + str(limit - count) + " more wrong guesses to hang\n")
            

        elif count == 2:
            print("Wrong guess. " + str(limit - count) + " more wrong guesses to hang\n")
          
        elif count == 3:
           print("Wrong guess. " + str(limit - count) + " more wrong guesses to hang\n")
           

        elif count == 4:
           print("Wrong guess. " + str(limit - count) + " more wrong guesses to hang\n")
           
        elif count == 5:
            print("Wrong guess. " + str(limit - count) + " more wrong guess to hang\n")
            

        elif count == 6:
            print("Wrong guess. GAME OVER!!!\n")
            print("The word was:",word)
            print("THANK YOU FOR PLAYING\n")
            break