# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hCF79yLykIausPQUEvev9v8KBL7trTAO
"""

sentence = 'Python is Awesome'

def reverseword(s): 
   
   w = sentence.split(" ")        
   new = [i[::-1] for i in w]                      
   reversedString = " ".join(new)
   return reversedString

print(reverseword(sentence))