# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A0REMT0vCrTzflUJuhw6nnJXL0T0m_kZ
"""

import random
import numpy as np
import pandas as pd
from pandas import DataFrame
import matplotlib.pyplot as plt
from IPython.display import display

words = []
with open('/content/words.txt') as f:
    for line in f:
        words.append(line.strip())

def pick_random_word():
    randomWord = random.choice(words)
    return randomWord
  

#Fetching Input
def ask_user_input(inputWord = None):
    while True:
        inputWord = input ("Enter a 5-letter Word :\n")
        if type(inputWord) != str or len(inputWord) != 5:
            print('Invalid Entry')
            continue
        else:
            return inputWord.upper()

#Change Letter Colors
def color_positive(val):
    if val == val.upper() and len(val) == 1:
        color = 'green'
    elif len(val) == 2:
        color = 'orange'
    else:
        color = 'black'
    return 'color: %s' % color

def build_df(attempt, guess_arr):
    cols = ['L1', 'L2', 'L3', 'L4', 'L5']
    idx = ['TRY_' + str(attempt +1)]
    
    df = pd.DataFrame(guess_arr).T
    df.columns = cols
    df.index = idx
    
    return df

def mark_letters(guess_idx):
    final = []
    for item in guess_idx:
        if item[2] == 'YES':
            final.append(item[0])
        elif item[2] == 'EX':
            final.append(item[0] + ' ')
        else:
            final.append(item[0].lower()) 
    return final


#---------GAME BEGINS--------------#

def play_wordle():

    print("Let's play WORDLE\n")

    print("COLOR INDICATIONS : \n1. GREEN : Correct letter at correct position\n2.ORANGE : Correct letter at wrong position\n3.BLACK : Wrong letter\n")

    randomWord = pick_random_word()
    
    true_arr = np.array(list(randomWord.upper())) #Turning true word into array of individual letters and indexes
    
    true_idx = [[item, idx, None] for idx, item in enumerate(true_arr)]
    
    attempt = 0
    guess_store = []
    
    while attempt < 6:
        #guess word
        guess_word = ask_user_input()
        guess_arr = np.array(list(guess_word))
        guess_idx = [[item, idx, None] for idx, item in enumerate(guess_arr)]

        matched = []
        existing = []
        matching = np.where(true_arr == guess_arr)[0]

        for item in matching:
            matched.append(guess_idx[item][0])
            guess_idx[item][2], true_idx[item][2] = 'YES', 'YES'

        rem_guess = [item for item in guess_idx if item[2] != 'YES']
        rem_true = [item for item in true_idx if item[2] != 'YES']

        for guess in rem_guess:
            for true in rem_true:
                if guess[0] == true[0]:
                    if list(true_arr).count(guess[0]) > (matched.count(guess[0]) + existing.count(guess[0])):
                        existing.append(guess[0])
                        guess[2], true[2] = 'EX', 'EX'
                    else:
                        continue
        
        #Coloring letters
        def color_positive(val):
            if val == val.upper() and len(val) == 1:
                color = 'green'
            elif len(val) == 2:
                color = 'orange'
            else:
                color = 'black'
            return 'color: %s' % color

        #Mark letters based on match, exist, or not exist
        final = mark_letters(guess_idx)
        
        #Turn current guess word into row in pandas DF
        guess_df = build_df(attempt, final)
        guess_store.append(guess_df)
        new_df = pd.concat(guess_store)
        
        #Use color_positive function to color letters
        s = new_df.style.applymap(color_positive)
        display(s)

        if guess_word.lower() == randomWord:
            print('##############################################################')
            print(f'       HURRAY THE WORD WAS: {randomWord.upper()} ')
            print('##############################################################')
            print('CONGRATULATIONS!!!YOU WON')
            print('Give yourself a pat on the shoulder :)')
            print("WANNA PLAY AGAIN?")
            break
        else:
            attempt += 1
            
            if attempt == 6:
                print(f'Sorry! The word was {randomWord.upper()}, BETTER LUCK NEXT TIME....')
                break

if __name__ == '__main__':
    play_wordle()
