# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hCF79yLykIausPQUEvev9v8KBL7trTAO
"""

number_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
for i in list(number_list):
    if i > 50:
        number_list.remove(i)
print(number_list)