# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CHl_BaI9wjyhWsR3PCpqXH9yT3tIhgC8
"""

##############change behavior of functions at compile time itself---property decoraters###############################  

class Employee:  
    def __init__(self, firstName, lastName):  
        self.firstName =firstName  
        self.lastName = lastName  
     
    @property  
    def fullName(self):  
        return self.firstName + ' ' + self.lastName  
  
    #setter for the full name  
    @fullName.setter  
    def fullName(self, name):   
        firstName, lastName = name.split(" ")  
        self.firstName = firstName  
        self.lastName = lastName  
  
    #deleter for full name  
    @fullName.deleter  
    def fullName(self):  
        self.firstName = None  
        self.lastName = None  
        print('Deleted the full name')  
  
    # generating email using first and last name  
    def email(self):  
        return '{}.{}@mail.com'.format(self.firstName, self.lastName)  
  
obj = Employee('Nandana', 'Vijayakumar')  
print('Fullname is:', obj.fullName)  
print('Email address is: ', obj.email())  
  
# updating the obj object's first name  
obj.firstName = 'Bhavya'  
print('Fullname of obj is: ', obj.fullName)  
print('And email address:', obj.email())  
  
#setting new value of full name  
obj.fullName = 'Smitha S'  
print('New Fullname of obj is:', obj.fullName)  
  
#deleting the full_name  
del obj.fullName